sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
notifications:
  email: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
- curl -s ${SCRIPTS}/setup-tests.sh | bash /dev/stdin
script:
- gradle check -i || exit 1
- curl -s ${SCRIPTS}/generate-bintray-descriptor.sh
  | bash /dev/stdin admin address-controller/server/build/distributions/server.tgz queue-scheduler/build/distributions/queue-scheduler.tgz configserv/build/distributions/configserv.tgz > .bintray.json
- curl -s ${SCRIPTS}/docker-build.sh | bash /dev/stdin enmasseproject/address-controller address-controller/server
- curl -s ${SCRIPTS}/docker-build.sh | bash /dev/stdin enmasseproject/configserv configserv
- curl -s ${SCRIPTS}/docker-build.sh | bash /dev/stdin enmasseproject/queue-scheduler queue-scheduler
- curl -s ${SCRIPTS}/run-tests.sh | bash /dev/stdin ${COMMIT} "" enmasseproject/address-controller enmasseproject/configserv enmasseproject/queue-scheduler || exit 1
after_success:
- curl -s ${SCRIPTS}/docker-push.sh | bash /dev/stdin enmasseproject/address-controller
- curl -s ${SCRIPTS}/docker-push.sh | bash /dev/stdin enmasseproject/configserv
- curl -s ${SCRIPTS}/docker-push.sh | bash /dev/stdin enmasseproject/queue-scheduler
env:
  global:
  - SCRIPTS=https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: pdYUIqs3YYtpDu3leNYV/T6H8rCfocCGEYL0wsy2N2W+PwGyQyV7h48pg3C+wL5cN1mNEuNEEFGkFvSlvt5XW+bP4u2ypQGQf2SSeEDTB/NEx18nDkWwGYxq79EcDeAriqbQCvO3GLyT5Uheh5/6A54Hg/qq6VnDptyN9AIhihKWms6OF9Y8lTKKPjBlIyvYXDNbYG8ths1WszBPCa1MJO+C/fhT0RkyxQz5y//pDU9FD/q9bIlN+bxTLZT9TFZKkiUaxVwreBJLNBnfOjbdBCzp4p0K4OQNB3ORZxjKiZowCuN4Rj29D6LW6vcy4+gOjbILlFzewgouCUJ7Q9wL9g5ypPAIZMbnKYUwdUi9niCmpdY1qJyC0GjCbI4yH0KOep114O6pOappAKOoXzoE+41yCb9Nh3TjYxlP+MwO6C4rMjsZclh+9gdm1uIF2yEkd23HwNWfwUXLJSO6cnnRSDaO+psS9E/jKUh4aVdClA+wG5eVJ2OS13At15909WI9MTFf3fwazjLancgEaEL7SqxJ1nBUEzoFSD7wnOY/T69IZHnvOnzWrHku1INrX3kdYH0u9Zi5JoaC4g40y8kG0jhaFJxPPGLiTs5HNLYKK1ka9KvN5gGCrb4Ca5e7ftDqcDt7XtqNNkgp4kXsFxUQ8Y31RCEZe+zJnwQ7oZQW75g=
  - secure: iV+3xS7j/e1yLiniUDYb5W+oF9pvmjdqAgQY+9E8U55UYycMiFMruJ8uBoyb02lPVp9Qa5VL02e4Lfax8Kdfr6zLqOFuWSVnAwk9a5m58LtYfLxKKHgK+u6hr4ABmt9vPOqRa5gOlzMNVAYZdOEKewdqOaC8pCQnxT7/Amdinq6/eLoMUpYjhZtG7Qb/OrPhqTXLPezzmyfbkG9MG410Ek6HMu+prfMJkXAg6Q1I5xlBypoSp/qMxuO09KP8DNYNpUS5n85tS+7GivAKxq1OBf431OqeZaFGpcJH2HXuVtQLlf7DtBwgGYWnvZNpRpXfCi63XzX2f3eOfFnKzEOA8x/OCO7xqGHjmjvNUfhjewz3T+TGU2lfPZV7yIhC7h/C3gD0lIe+7cXMAFSbsPUUrVdI6eVpvp79n2yec+zmtRJS5zqwOdVXP3kNQOlOmf4QVk2VN8L5TKoYX9sFyGHmGc+CDj5ZRNe3/6Z7Rfh9WwpoEusBE+L2rH2CVEuU0MK6kZByvl4TkEQ0ylfKHSaALd29VUblqKZAbgr2zfibGpwmGdqvaJK4fB7wLkJ+of0nHmvC8wLN4Z8h9hYXbsoRq27R6Atd6mVtPb5A8fE/HefqsvGkYDe1aRUh/yzSTKuWgQl+XlmesDZ2q16+fwMk++Rfkoop3qRh1a1qakBPY9Q=
  - secure: FJzlJCCif38TrkFGFtEecQ72kHWn7GW9u8NaCah0Q0uWGJXDujhiQ4vpka+xuAnzows3VXVf8jnXEiRcscEET4lyeZk8e/jrLuLvFrae+iH4fNMTp80Lt+R8UCd0rCKJfV9v+avS3wFwlYLuvzixVdu6jOXaOF9ocYBozDOIP69Nf90fpRomwERD4p4iSWn25E+t2hycrt/9nL+bCgPUSHyPLIsDS5lM4vJM8iBPQR3hDlt9hcAdq9tvUcaa307qja7suTp4KkBJQkPCZn9QIAQ6Ad+aytRZGCFmgqqf3cauGI7cLiigIQ+HG4BFMLKRaIa2uRcOL7jrw8sT89XE5Ro6Phxbku2feysYAxY2X1PiSHf+0Ig6TO+fA4wWY99jWQAE3p0ZshcKECvcxXcjfToS79q82MBfMQQ673pci2IPRZLxb0j5z4/ciaIPkig0KSj7KDlLYqk8L30VnFo8sUzSuZk9mSLmKfZ3dSH79psY1pBR1phBlEfV6M9zolEIhljYZTy+PGLwnnPmCss2M5o0t06hxHAT0EvzhCg5tv5X/pV+LeAw8Uicjf9K+UMc7B9HA+FYuvtU0CCIOTRAd/TYjoK6gdc+XJRqJJvIdoUKEs2VXeFWOS3+iRREnh/sf77tHj07YfjLcF2Pom3vGDS0dJ/Inx8rJof8hHEabZ8=
  - secure: B17aK1fdkdXOmXqblXUX8qq9DvP4xSAhken27pl3BlXpmDnQgfVoHdk/+vzs9Po46Zqz9nT/UjpuRKBAJcn4BPAz17F3W2ue334DnW0UcshyuP+DXxajAaGa2jaaWJSi59GJs8SsJ/yEoc0VfXEqU26rmVwchKUDbi3y17BEz+kKxGdMCj4pJXMAmioxyke9icBByprfnQ6bnE7bkedm4AJbTLdC3JioyNpA5oG/Ysi1iTRe1ELJ1GBZ7xElFl8Hr8QqruzJqCQUQn4ah9ja+7jpscv1M/ACl0q7hv+4iqrXYPHNXIPlpKugVIBPwEES41NUQS//fNuC25hrbqqAaQ36t4PQ8YcCXZSgXdtTZoSfebdgTaxj+5Ug+P5CcicAd7patPHkog3r36X3JwLG9GaqtJHdUAvU6wHLazjxhHKsrpUec6LzfUP4WwzGOj87+apBsbKxqdo36S+D1PbzeL6ZgmiSUL27heLFGHD1G/4eiuDs8/bgTLHiqzQsbnNchRtvboywwyT/OmiZmiUeIqGEaGSQQlUYEBaWrmhqi3ZPi8SXn7I3CEDU3v23/hWFb3Ixa95NhoEFqXe92KQfs05ESrCLtruR2WwM8by4RdLXT0nfE1lsX14c5VBQc1dGnfWxu4Kf3OJ+TJdxzzPHa1gtjs5j6c8eZS/vdNvByI0=
deploy:
  - provider: bintray
    file: ".bintray.json"
    user: "${BINTRAY_API_USER}"
    on:
      tags: true
    key:
      secure: BIcYIVhjd7yQ7lFod6Oz8kMI9ZVIwyj/mmqilDqx5e1DHBOcOQSZGLWX6ikPCLF+lsCFOAX7BkUk53HlltYadYjkEhK0e5uXn3wOFEVvV03T3QJ3NdhnKan9LrgLwYwqx9NFJrvW+fTJbXZh8FUyRuNC32o1fYYoDrL2S5ItzIwTPfkbZY44if4fRIw2lM3fysalPsuG7pFDp5kOqvrCQBtVX19wwrqdmNPGmM67E56b5nRtDaNgyXUj0dTeNqfazFq8aqTTEdlSH6MPlclfom+mZeTrO2jtIVuLE+TmyyevsvFZcDtf/TFV98kEqfgoWLWJhTfRjfhfUDCvKMrwQKGXNd9AMD504Gnn4vg8r9yxQdI0rf8WfUEs/yhbHqGipmUmP9SspVN4ayKnMcB8TwBnuZEPYxO090AFrES/++4tX9AXEB8x13mmIuI/MarbrBsqqisYo7GqTP+xUpQDt2QUd0W2S51rQYYYdlBM1ZcOgzMUn8QMQ77vdGMOWCZdSQ88Pee7PcnIb66UXKUx+rnteRTXvk1Z/ZocRc7O7PBdR8apbR3oa1U2wfFmD4jXs+44Bm4vlI6uPLACqJssJDEjsOSJWEcUTVuoPgaDOptMWIiLbVqq8hgNjDqcRD9hmNsq7Ln9gMBg5QFmWairHT7D8/fFhP59DOdGG1gHn4Q=
  - provider: bintray
    file: ".bintray.json"
    user: "${BINTRAY_API_USER}"
    key:
      secure: BIcYIVhjd7yQ7lFod6Oz8kMI9ZVIwyj/mmqilDqx5e1DHBOcOQSZGLWX6ikPCLF+lsCFOAX7BkUk53HlltYadYjkEhK0e5uXn3wOFEVvV03T3QJ3NdhnKan9LrgLwYwqx9NFJrvW+fTJbXZh8FUyRuNC32o1fYYoDrL2S5ItzIwTPfkbZY44if4fRIw2lM3fysalPsuG7pFDp5kOqvrCQBtVX19wwrqdmNPGmM67E56b5nRtDaNgyXUj0dTeNqfazFq8aqTTEdlSH6MPlclfom+mZeTrO2jtIVuLE+TmyyevsvFZcDtf/TFV98kEqfgoWLWJhTfRjfhfUDCvKMrwQKGXNd9AMD504Gnn4vg8r9yxQdI0rf8WfUEs/yhbHqGipmUmP9SspVN4ayKnMcB8TwBnuZEPYxO090AFrES/++4tX9AXEB8x13mmIuI/MarbrBsqqisYo7GqTP+xUpQDt2QUd0W2S51rQYYYdlBM1ZcOgzMUn8QMQ77vdGMOWCZdSQ88Pee7PcnIb66UXKUx+rnteRTXvk1Z/ZocRc7O7PBdR8apbR3oa1U2wfFmD4jXs+44Bm4vlI6uPLACqJssJDEjsOSJWEcUTVuoPgaDOptMWIiLbVqq8hgNjDqcRD9hmNsq7Ln9gMBg5QFmWairHT7D8/fFhP59DOdGG1gHn4Q=
